ROLE_ADMIN = "admin"
ROLE_RESEARCHER = "researcher"
ROLE_USER = "user"

REVIEW_PENDING = "pending"
REVIEW_APPROVED = "approved"
REVIEW_REJECTED = "rejected"

ACCOUNT_NORMAL = "normal"
ACCOUNT_LOCKED = "locked"
ACCOUNT_BANNED = "banned"

MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_MINUTES = 15
